Server:
  Port: 5005
  RunMode: debug
Logger:
  FilePath: ../logs/logs.log
  Encoding: json
  Level: debug
cors:
  AllowOrigins: "*"
Postgres:
  Host: postgres_container
  Port: 5432
  User: postgres
  Password: admin
  DbName: car_sale_db
  sslName: false
redis:
  Host: redis_container
  Port: 5432
  Password: password
  Db: 0
  MinIdConnections: 100
  PoolSize: 5000
  PollTimeOut: 240
